function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, U1, V1)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, U1, V1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  quiver x
%  Y6:  quiver y
%  U1:  quiver u
%  V1:  quiver v

%  Auto-generated by MATLAB on 24-May-2014 20:59:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YMinorTick','on','YColor',[0.3 0.3 0.3],...
    'XMinorTick','on',...
    'XColor',[0.3 0.3 0.3],...
    'TickDir','out',...
    'TickLength',[0.02 0.02],...
    'PlotBoxAspectRatio',[1 1 1],...
    'LineWidth',1);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-1 1]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-1 1]);
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'DisplayName','t = 0.00 s');

% Create plot
plot(X2,Y2,'Parent',axes1,'DisplayName','t = 0.40 s');

% Create plot
plot(X3,Y3,'Parent',axes1,'DisplayName','t = 0.80 s');

% Create plot
plot(X4,Y4,'Parent',axes1,'DisplayName','t = 1.20 s');

% Create plot
plot(X5,Y5,'Parent',axes1,'DisplayName','t = 1.60 s');

% Create quiver
quiver(X6,Y6,U1,V1,'Parent',axes1,'DisplayName','Velocity Vector');

% Create text
text('Parent',axes1,...
    'String',['n = 200',sprintf('\n'),'\Deltat = 0.1\Deltax = 0.0010',sprintf('\n'),'\Deltax = L/(N-1) = 0.0101'],...
    'Position',[-0.95 0 0],...
    'EdgeColor',[0 0 0],...
    'BackgroundColor',[1 1 1]);

% Create title
title('Contour Plot of $\mathbf{\phi}$ with velocity vectors',...
    'Interpreter','latex');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','SouthEast','LineWidth',1);

