figure(5);clf;
   hold on;
   L=2;
axis([-.6,.6,0,1.2])
axis('square')
plot(xTn(:,end),yTn(:,end),'o')
axis([-.6 .6 .1 1.3])
axis('square')
hXLabel = xlabel('x');
hYLabel = ylabel('y');
% Create axes
% hText = text(-0.95,0,...
%     [sprintf('N = %g\n\\Deltat = 0.1',n) sprintf(' = %4.4f\n\\Deltax = L/(N-1) = %4.4f',dt,dx)],...
%     'EdgeColor',[0 0 0],...
%     'BackgroundColor',[1 1 1]);
%
% hLegend = legend(...
%     sprintf('Front Tracking'),...
%     sprintf('Level Set'),...
%     'location','SouthEast');
hTitle = title('Front-Tracking: Distribution of markers','Interpreter','latex')
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([gca]             , ...
    'FontSize'   , 8           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
    'Box'         , 'off'         , ...
    'TickDir'     , 'out'         , ...
    'TickLength'  , [.02 .02]     , ...
    'XMinorTick'  , 'on'          , ...
    'YMinorTick'  , 'on'          , ...
    'YGrid'     ,'on',...
    'XColor'      , [.3 .3 .3]    , ...
    'YColor'      , [.3 .3 .3]    , ...
    'LineWidth'   , 1             );
hold off;

printYesNo = 1;
if printYesNo == 1
    saveFigurePath = ['/Users/kevin/SkyDrive/KTH Work/Period' ...
        ' 3 2014/DN2255/Homework/5/Figures/'];
    addpath(saveFigurePath);
    set(gcf, 'PaperPositionMode', 'auto');
    print('-depsc2', [saveFigurePath ...
        sprintf('frontMarkers')]);
end